language: node_js
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # from travis-ci settings page
  keep-history: true
  on:
    branch: master