language: node_js
script:
  - npm ci
  - npm run ci
  - sed -i "s,__SENTRY_DSN__,${SENTRY_DSN}," src/index.js
  - sed -i "s,__SENTRY_RELEASE__,${TRAVIS_COMMIT}," src/index.js
  - npm run build
branches:
  # Travis is configured to build branches and PRs. Need to
  # restrict branch builds to just master branch, otherwise
  # PRs from same repo are built twice.
  only:
    - master
deploy:
  - skip_cleanup: true
  - provider: script
    script: npm run sentry-cli -- releases new -p react-game "${TRAVIS_COMMIT}" && npm run sentry-cli -- releases set-commits --auto "${TRAVIS_COMMIT}"
    on:
      branch: master
  - provider: pages
    local-dir: build
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # from travis-ci settings page
    keep-history: true
    on:
      branch: master
