name: checks

on: push

jobs:
  checks:
    runs-on: ubuntu-20.04
    permissions:
      contents: read

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'

    - run: npm ci
    
    - run: npm run ci

    - name: Build
      env:
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        GOOGLE_ANALYTICS_TRACKING_ID: ${{ secrets.GOOGLE_ANALYTICS_TRACKING_ID }}
      run: npm run build

    - name: Upload artifact
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-pages-artifact@v3.0.0
      with:
        name: react-game
        path: build

  deploy:
    needs: checks
    runs-on: ubuntu-20.04
    permissions:
      pages: write
      id-token: write
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'

    - run: npm ci

    - name: sentry pre release
      env:
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN}}
      run: |
        npm run sentry-cli -- releases new -p react-game "react-game@${GITHUB_SHA}"
        npm run sentry-cli -- releases set-commits --auto "react-game@${GITHUB_SHA}"

    - uses: actions/deploy-pages@v4.0.2
      id: deployment
      with:
        artifact_name: react-game

    - name: sentry post release
      env:
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN}}
      run: npm run sentry-cli -- releases deploys "react-game@${GITHUB_SHA}" new -e production

  # TODO prevent repetition of react-game@${GITHUB_SHA}
  # TODO prevent repetition of "react-game" artifact name
